apiVersion: v1
kind: Secret
metadata:
  name: my-docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsiYXV0aCI6IndhY2ltc2FpOjEyNDM3aG5pYyJ9fX0=
